### ISSUE TITLE
Underwater music still plays despite the player not being underwater anymore

### ISSUE THREAD

**Issue by vistis** [Modflower/music-moods#1]
### Environment

- **Minecraft**: 1.19.2 Client (Windows 11)
- **Music Moods**: 0.0.4
- **Mod Loader**: Quilt
- **Java**: 17.0.6

### To reproduce

1. Get underwater (the music changes to an underwater related track as expected)
2. Get out of the water (the underwater music still continues to play)

### Expected results

For the music to fade out.

### Actual results

The music never faded out.

### Anything else?

**Other Info:**
- I use a mod called "Music Notification" that basically shows what music is playing at the moment, so it's really helpful for demonstrating this bug. You can tell if the music has changed or not by looking at the toast.
- I set the fade in and fade out duration to 200 ticks.

**Expected behavior:** https://drive.google.com/file/d/1Jcv8PsbbqbxSojxPkCG_7qba0Kcmtc0B/view?usp=share_link

**Bug Demonstration:** https://drive.google.com/file/d/1fkaNE3Ul_m-3NNzJdF7U_mvXaBcWuVjT/view?usp=share_link

_Also, after triggering the bug, the underwater tracks keep playing non-stop; it won't change to other situational tracks besides the underwater ones, ever. It acts as if the player is still underwater, even though they are not._

**Comment by Ampflower** [comment]
Haven't noted the looping part before.

So, I wonder if it has to do with the Mojang method doing something weird that causes it to evaluate incorrectly.

**Comment by vistis** [comment]
Hmm, maybe. I don't know much about how the game works, but I noticed that in the vanilla game, after you've gotten an underwater track to play and then leave the water, it will just play regular tracks once the underwater track ends.

**Comment by Ampflower** [comment]
Yeah, that's how it should be; I'm just thinking on how would it get stuck since it should be updating automatically.

**Comment by vistis** [comment]
Hi again, it's been a while. Sorry for bugging you, but do you plan on fixing this issue?

**Comment by Ampflower** [comment]
Sorry, kinda have been on other things for the past while.

Creative music seems to also persist going into spectator as well, which I don't believe is vanilla; tho unrelated to this.

**Comment by Ampflower** [comment]
Root found for this particular issue: When under water music is playing, and it's in continuous mode, Minecraft continuously returns underwater music due to it not checking whether the player is still underwater when queuing.

**Comment by vistis** [comment]
That does complicate things a little. To fix it, maybe you have to override the vanilla music queueing system somehow.
