### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by vistis** [Modflower/music-moods#2]
### What would you like to be added?

As the title suggests.

I really like this mod, it really enhances the Minecraft experience by eliminating silences and improving the overall atmosphere with the dynamic music system corresponding to the biome the player is in. I hope that this mod continues to get updated.

**Comment by Ampflower** [comment]
Stalled on Modrinth.

**Comment by Ampflower** [comment]
v0.3.2 is now released

Apparently Minotaur requires the ability to read user data.
